### ISSUE TITLE
Code Review by Leyang Yu

### ISSUE THREAD

**Issue by LeyangYu1996** [8128/EC601#1]
Hi, This is Leyang Yu. I have downloaded your code and tried to use it using some different twitter ID. The code is basically all right, it can do what I expect it to do and the output video is fantastic. However, there is still some  problem that I think you can improve in the future. 

The first is that the program will just download all the pictures from that account, which might be too much if the owner of the account is active. In this case, it might take a long time for my computer to handle it and it can take a lot of storage space. I will really appreciate if you can improve this problem by simply adjusting the loop.

The second is that when error occurs, the feedback, or the performance that the program has, can be improved. For example, if I try to download some pictures from a twitter account that has no tweets or no pictures in it, the program will stop and the feedback is hard to analysis. This can also happen when authorization is not completed or the format of picture is not 'jpeg'. So if you can add some 'if' and 'try' to improve the performance when error occurred, that will be good.

After all, it is still a good program and I hope to see it being improved!

**Comment by 8128** [comment]
Hi Leyang Yu:

Thanks for your review, I will solve these problems and update the scripts later.
Many thanks for your time and patience.

Tianyi Tang
